# Google Cloud Run deployment configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: poetry-app
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # CPU and Memory allocation
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/memory: "512Mi"
        # Scaling settings
        run.googleapis.com/min-instances: "1"
        run.googleapis.com/max-instances: "10"
        # Connection settings
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
        - image: gcr.io/PROJECT_ID/poetry-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: poetry-secrets
                  key: database_url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: poetry-secrets
                  key: jwt_secret
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
