export const routes = {
  home: 'home',
  profile: 'profile',
  search: 'search',
  favorites: 'favorites',
  // recites: 'recites',
  reciteCollection: 'reciteCollection',
  collectionPoet: 'collectionPoet',
  finished: 'finished',
  aboutUs: 'aboutUs',
  poetModal: 'poetModal',
  searchModal: 'searchModal',
  login: 'login',
  register: 'register',
};
