export const ADD_COLLECTION = 'recite/ADD_COLLECTION';
export const ADD_COLLECTION_SUCCESS = 'recite/ADD_COLLECTION_SUCCESS';
export const ADD_COLLECTION_ERROR = 'recite/ADD_COLLECTION_ERROR';

export const ADD_POET_TO_COLLECTION = 'recite/ADD_POET_TO_COLLECTION';
export const ADD_POET_TO_COLLECTION_SUCCESS = 'recite/ADD_POET_TO_COLLECTION_SUCCESS';
export const ADD_POET_TO_COLLECTION_ERROR = 'recite/ADD_POET_TO_COLLECTION_ERROR';

export const FINISH_COLLECTION = 'recite/FINISH_COLLECTION';
export const FINISH_COLLECTION_SUCCESS = 'recite/FINISH_COLLECTION_SUCCESS';
export const FINISH_COLLECTION_ERROR = 'recite/FINISH_COLLECTION_ERROR';
