export const ADD_COLLECTION = 'recite/ADD_COLLECTION';
export const ADD_COLLECTION_SUCCESS = 'recite/ADD_COLLECTION_SUCCESS';
export const ADD_COLLECTION_ERROR = 'recite/ADD_COLLECTION_ERROR';

export const ADD_POETRY_TO_COLLECTION = 'recite/ADD_POETRY_TO_COLLECTION';
export const ADD_POETRY_TO_COLLECTION_SUCCESS = 'recite/ADD_POETRY_TO_COLLECTION_SUCCESS';
export const ADD_POETRY_TO_COLLECTION_ERROR = 'recite/ADD_POETRY_TO_COLLECTION_ERROR';

export const DELETE_POETRY_FROM_COLLECTION = 'recite/DELETE_POETRY_FROM_COLLECTION';
export const DELETE_POETRY_FROM_COLLECTION_SUCCESS = 'recite/DELETE_POETRY_FROM_COLLECTION_SUCCESS';
export const DELETE_POETRY_FROM_COLLECTION_ERROR = 'recite/DELETE_POETRY_FROM_COLLECTION_ERROR';

export const FINISH_COLLECTION = 'recite/FINISH_COLLECTION';
export const FINISH_COLLECTION_SUCCESS = 'recite/FINISH_COLLECTION_SUCCESS';
export const FINISH_COLLECTION_ERROR = 'recite/FINISH_COLLECTION_ERROR';

export const DELETE_COLLECTIONS = 'recite/DELETE_COLLECTIONS';
export const DELETE_COLLECTIONS_SUCCESS = 'recite/DELETE_COLLECTIONS_SUCCESS';
export const DELETE_COLLECTIONS_ERROR = 'recite/DELETE_COLLECTIONS_ERROR';
