export const FETCH_RECOMMENDATION = 'recommendation/FETCH_RECOMMENDATION';
export const FETCH_RECOMMENDATION_SUCCESS = 'recommendation/FETCH_RECOMMENDATION_SUCCESS';
export const FETCH_RECOMMENDATION_ERROR = 'recommendation/FETCH_RECOMMENDATION_ERROR';
